version: '2.0'

networks:
  twist_net:

services:

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: validator
    expose:
      - 4004
    ports:
      - '4004:4004'
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key &&
          sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800"
    networks:
      - twist_net

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004
    networks:
      - twist_net

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind rest-api:8008
    networks:
      - twist_net

  python_tp:
    build:
      context: ./ 
      dockerfile: ./transactionProcessor/Dockerfile
    container_name: python-tp
    depends_on:
      - validator
    command: python3 main.py -C tcp://validator:4004
    volumes:
      - ./transactionProcessor:/project
    networks:
      - twist_net

  application:
    image: node:8.15.0-jessie
    container_name: application
    volumes:
      - ./node_app:/twist/node_app
    working_dir:  /twist/node_app
    command: |
      bash -c "
        set -x &&
        npm install
        tail -f /dev/null
      "
    depends_on:
      - python_tp
    networks:
      - twist_net
